### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by kanghyun98** [gdsc-ssu/sasil-front#26]
## 테크 스펙 (Tech Spec)
https://www.notion.so/ced6d140f3514a29bf4ec15785f64750

## 마일스톤 (Milestones)
이슈 만들면 링크 연결해주세요!
- [x] https://github.com/gdsc-ssu/sasil-front/issues/27
- [x] https://github.com/gdsc-ssu/sasil-front/issues/29
- [x] 전체 컴포넌트 UI 작업 (Front)
- [ ] `@sasil/common` 메인 피드 관련 API 연결 및 전역 상태 관리 (Front)
- [ ] 로그인 상태에 따른 페이지 이동 (Front)
- [x] https://github.com/gdsc-ssu/sasil-server/issues/22
- [x] https://github.com/gdsc-ssu/sasil-server/issues/21
- [x] https://github.com/gdsc-ssu/sasil-server/issues/24
