### ISSUE TITLE
메인 페이지용 게시물 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by ballsona** [gdsc-ssu/sasil-front#27]
## Epic
메인 페이지 https://github.com/gdsc-ssu/sasil-front/issues/26 
## Description
메인 페이지에서 사용될 게시물 컴포넌트 UI를 구현한다. 
게시물 내에 들어갈 `좋아요`, `작성자` 등을 Atom 단위로 구현하고, 이를 조합하여 게시물 Molecule 을 생성한다.  
이때 게시물 컨텐츠가 `실험`인지 `의뢰`인지에 따라 게시물 내에 들어갈 정보에 차이가 있으므로 이를 유의하여 구현한다.
## TODO

- [ ] 좋아요 컴포넌트, 작성자 컴포넌트 Atom 단위로 생성
- [ ] 게시물 컴포넌트 Molecule 단위로 생성
- [ ] UI를 위한 Storybook 
- [ ] Web용, Mobile용 컴포넌트 모두 생성할 것
