### ISSUE TITLE
네비게이션 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by kanghyun98** [gdsc-ssu/sasil-front#29]
## Epic
#26 

## Description
전체 페이지에서 사용될 네비게이션 컴포넌트 UI를 구현한다. 추가적으로 메인페이지에서 사용할 글 작성 버튼 UI도 함께 구현한다.

## TODO
- [ ] 웹은 검색 및 페이지 이동이 가능한 상단 바 컴포넌트 생성
- [ ] 모바일은 페이지 이동이 가능한 하단 바 컴포넌트를 생성한다.
- [ ] 게시물 작성 버튼 컴포넌트를 생성
- [ ] 버튼 클릭 시, 특정 페이지로 이동 기능 구현 (드롭박스가 있다면 그것까지)
- [ ] 웹에서 반응형 페이지 적용
