### ISSUE TITLE
회원 탈퇴 api 추가

### ISSUE THREAD

**Issue by kanghyun98** [gdsc-ssu/sasil-front#69]
## Epic
#68 

## Description
회원 탈퇴 api 추가 및 유저 정보 관련 타입 및 반환 데이터 수정

## TODO
- [x] 회원 탈퇴 api 추가
- [x] 유저 정보 조회에서 이메일, 로그인 타입 정보 삭제
- [x] 탈퇴한 유저의 null 타입 처리 및 관련 로직 수정
