### ISSUE TITLE
유저페이지 컴포넌트 UI 구현 (웹)

### ISSUE THREAD

**Issue by kanghyun98** [gdsc-ssu/sasil-front#79]
## Epic
#76 

## Description
웹에서의 유저페이지를 위한 컴포넌트 구현

## TODO
- [x] 아토믹 구조에 따른 컴포넌트 구현
- [x] 반응형 디자인 반영
- [x] API 작업 (Infinite Scroll)
