### ISSUE TITLE
검색 페이지 UI 관련 리팩토링 

### ISSUE THREAD

**Issue by ballsona** [gdsc-ssu/sasil-front#90]
## Epic
#77 
## Description
검색 결과 페이지 UI를 수정합니다. 
<img width="1362" alt="스크린샷 2022-11-01 13 52 03" src="https://user-images.githubusercontent.com/67703882/199161587-52a35bf9-ad32-4552-af02-84736b4fbecd.png">

## TODO

- [ ] 검색 결과가 없을 경우 보여지는 문구를 추가
- [ ] 검색 결과 게시물 리스트가 중앙 정렬되고 있는 부분을 수정 
- [ ] Toggle 버튼 유저 페이지와 통일

**Comment by ballsona** [comment]
오예~~~~~~~~~
